apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-echo-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esp-echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
      - name: echo
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
#           limits:
#             memory: "Mi"
#             cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: esp-echo
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: esp-echo
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esp-echo
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "dhani-static-ip"
spec:
  tls:
  - secretName: dhani-cloud-tls
  rules:
  - host: "dev-esp-echo.dhani.cloud"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: esp-echo
            port:
              number: 80
