name: Build
on:
  workflow_call:
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - 16
        os:
        - ubuntu-latest
    steps:
      # Prepare Repository
      - name: Prepare
        uses: actions/checkout@v3
      # Setup Only If Using Event Reusable Workflows
      - name: Set Up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.java-version }}
      - name: Installing Packages
        run: yarn install --pure-lockfile

